package ent

//go:generate go run entgo.io/ent/cmd/ent generate --header "// Code generated by ent, DO NOT EDIT." --target ./db ./schema

// This single-line directive achieves the same result as the multi-line version.