// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/platformapprole"
	"github.com/dexidp/dex/storage/ent/db/platformfederatedidentity"
	"github.com/dexidp/dex/storage/ent/db/platformidentityroleassignment"
	"github.com/dexidp/dex/storage/ent/db/predicate"
)

// PlatformIdentityRoleAssignmentQuery is the builder for querying PlatformIdentityRoleAssignment entities.
type PlatformIdentityRoleAssignmentQuery struct {
	config
	ctx          *QueryContext
	order        []platformidentityroleassignment.OrderOption
	inters       []Interceptor
	predicates   []predicate.PlatformIdentityRoleAssignment
	withIdentity *PlatformFederatedIdentityQuery
	withRole     *PlatformAppRoleQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlatformIdentityRoleAssignmentQuery builder.
func (piraq *PlatformIdentityRoleAssignmentQuery) Where(ps ...predicate.PlatformIdentityRoleAssignment) *PlatformIdentityRoleAssignmentQuery {
	piraq.predicates = append(piraq.predicates, ps...)
	return piraq
}

// Limit the number of records to be returned by this query.
func (piraq *PlatformIdentityRoleAssignmentQuery) Limit(limit int) *PlatformIdentityRoleAssignmentQuery {
	piraq.ctx.Limit = &limit
	return piraq
}

// Offset to start from.
func (piraq *PlatformIdentityRoleAssignmentQuery) Offset(offset int) *PlatformIdentityRoleAssignmentQuery {
	piraq.ctx.Offset = &offset
	return piraq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piraq *PlatformIdentityRoleAssignmentQuery) Unique(unique bool) *PlatformIdentityRoleAssignmentQuery {
	piraq.ctx.Unique = &unique
	return piraq
}

// Order specifies how the records should be ordered.
func (piraq *PlatformIdentityRoleAssignmentQuery) Order(o ...platformidentityroleassignment.OrderOption) *PlatformIdentityRoleAssignmentQuery {
	piraq.order = append(piraq.order, o...)
	return piraq
}

// QueryIdentity chains the current query on the "identity" edge.
func (piraq *PlatformIdentityRoleAssignmentQuery) QueryIdentity() *PlatformFederatedIdentityQuery {
	query := (&PlatformFederatedIdentityClient{config: piraq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piraq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piraq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(platformidentityroleassignment.Table, platformidentityroleassignment.FieldID, selector),
			sqlgraph.To(platformfederatedidentity.Table, platformfederatedidentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, platformidentityroleassignment.IdentityTable, platformidentityroleassignment.IdentityColumn),
		)
		fromU = sqlgraph.SetNeighbors(piraq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRole chains the current query on the "role" edge.
func (piraq *PlatformIdentityRoleAssignmentQuery) QueryRole() *PlatformAppRoleQuery {
	query := (&PlatformAppRoleClient{config: piraq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piraq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piraq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(platformidentityroleassignment.Table, platformidentityroleassignment.FieldID, selector),
			sqlgraph.To(platformapprole.Table, platformapprole.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, platformidentityroleassignment.RoleTable, platformidentityroleassignment.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(piraq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PlatformIdentityRoleAssignment entity from the query.
// Returns a *NotFoundError when no PlatformIdentityRoleAssignment was found.
func (piraq *PlatformIdentityRoleAssignmentQuery) First(ctx context.Context) (*PlatformIdentityRoleAssignment, error) {
	nodes, err := piraq.Limit(1).All(setContextOp(ctx, piraq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{platformidentityroleassignment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) FirstX(ctx context.Context) *PlatformIdentityRoleAssignment {
	node, err := piraq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PlatformIdentityRoleAssignment ID from the query.
// Returns a *NotFoundError when no PlatformIdentityRoleAssignment ID was found.
func (piraq *PlatformIdentityRoleAssignmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piraq.Limit(1).IDs(setContextOp(ctx, piraq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{platformidentityroleassignment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) FirstIDX(ctx context.Context) int {
	id, err := piraq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PlatformIdentityRoleAssignment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PlatformIdentityRoleAssignment entity is found.
// Returns a *NotFoundError when no PlatformIdentityRoleAssignment entities are found.
func (piraq *PlatformIdentityRoleAssignmentQuery) Only(ctx context.Context) (*PlatformIdentityRoleAssignment, error) {
	nodes, err := piraq.Limit(2).All(setContextOp(ctx, piraq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{platformidentityroleassignment.Label}
	default:
		return nil, &NotSingularError{platformidentityroleassignment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) OnlyX(ctx context.Context) *PlatformIdentityRoleAssignment {
	node, err := piraq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PlatformIdentityRoleAssignment ID in the query.
// Returns a *NotSingularError when more than one PlatformIdentityRoleAssignment ID is found.
// Returns a *NotFoundError when no entities are found.
func (piraq *PlatformIdentityRoleAssignmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piraq.Limit(2).IDs(setContextOp(ctx, piraq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{platformidentityroleassignment.Label}
	default:
		err = &NotSingularError{platformidentityroleassignment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := piraq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PlatformIdentityRoleAssignments.
func (piraq *PlatformIdentityRoleAssignmentQuery) All(ctx context.Context) ([]*PlatformIdentityRoleAssignment, error) {
	ctx = setContextOp(ctx, piraq.ctx, ent.OpQueryAll)
	if err := piraq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PlatformIdentityRoleAssignment, *PlatformIdentityRoleAssignmentQuery]()
	return withInterceptors[[]*PlatformIdentityRoleAssignment](ctx, piraq, qr, piraq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) AllX(ctx context.Context) []*PlatformIdentityRoleAssignment {
	nodes, err := piraq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PlatformIdentityRoleAssignment IDs.
func (piraq *PlatformIdentityRoleAssignmentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piraq.ctx.Unique == nil && piraq.path != nil {
		piraq.Unique(true)
	}
	ctx = setContextOp(ctx, piraq.ctx, ent.OpQueryIDs)
	if err = piraq.Select(platformidentityroleassignment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) IDsX(ctx context.Context) []int {
	ids, err := piraq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piraq *PlatformIdentityRoleAssignmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piraq.ctx, ent.OpQueryCount)
	if err := piraq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piraq, querierCount[*PlatformIdentityRoleAssignmentQuery](), piraq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) CountX(ctx context.Context) int {
	count, err := piraq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piraq *PlatformIdentityRoleAssignmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piraq.ctx, ent.OpQueryExist)
	switch _, err := piraq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piraq *PlatformIdentityRoleAssignmentQuery) ExistX(ctx context.Context) bool {
	exist, err := piraq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlatformIdentityRoleAssignmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piraq *PlatformIdentityRoleAssignmentQuery) Clone() *PlatformIdentityRoleAssignmentQuery {
	if piraq == nil {
		return nil
	}
	return &PlatformIdentityRoleAssignmentQuery{
		config:       piraq.config,
		ctx:          piraq.ctx.Clone(),
		order:        append([]platformidentityroleassignment.OrderOption{}, piraq.order...),
		inters:       append([]Interceptor{}, piraq.inters...),
		predicates:   append([]predicate.PlatformIdentityRoleAssignment{}, piraq.predicates...),
		withIdentity: piraq.withIdentity.Clone(),
		withRole:     piraq.withRole.Clone(),
		// clone intermediate query.
		sql:  piraq.sql.Clone(),
		path: piraq.path,
	}
}

// WithIdentity tells the query-builder to eager-load the nodes that are connected to
// the "identity" edge. The optional arguments are used to configure the query builder of the edge.
func (piraq *PlatformIdentityRoleAssignmentQuery) WithIdentity(opts ...func(*PlatformFederatedIdentityQuery)) *PlatformIdentityRoleAssignmentQuery {
	query := (&PlatformFederatedIdentityClient{config: piraq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piraq.withIdentity = query
	return piraq
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (piraq *PlatformIdentityRoleAssignmentQuery) WithRole(opts ...func(*PlatformAppRoleQuery)) *PlatformIdentityRoleAssignmentQuery {
	query := (&PlatformAppRoleClient{config: piraq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piraq.withRole = query
	return piraq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UpdateTime time.Time `json:"update_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PlatformIdentityRoleAssignment.Query().
//		GroupBy(platformidentityroleassignment.FieldUpdateTime).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (piraq *PlatformIdentityRoleAssignmentQuery) GroupBy(field string, fields ...string) *PlatformIdentityRoleAssignmentGroupBy {
	piraq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlatformIdentityRoleAssignmentGroupBy{build: piraq}
	grbuild.flds = &piraq.ctx.Fields
	grbuild.label = platformidentityroleassignment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UpdateTime time.Time `json:"update_time,omitempty"`
//	}
//
//	client.PlatformIdentityRoleAssignment.Query().
//		Select(platformidentityroleassignment.FieldUpdateTime).
//		Scan(ctx, &v)
func (piraq *PlatformIdentityRoleAssignmentQuery) Select(fields ...string) *PlatformIdentityRoleAssignmentSelect {
	piraq.ctx.Fields = append(piraq.ctx.Fields, fields...)
	sbuild := &PlatformIdentityRoleAssignmentSelect{PlatformIdentityRoleAssignmentQuery: piraq}
	sbuild.label = platformidentityroleassignment.Label
	sbuild.flds, sbuild.scan = &piraq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlatformIdentityRoleAssignmentSelect configured with the given aggregations.
func (piraq *PlatformIdentityRoleAssignmentQuery) Aggregate(fns ...AggregateFunc) *PlatformIdentityRoleAssignmentSelect {
	return piraq.Select().Aggregate(fns...)
}

func (piraq *PlatformIdentityRoleAssignmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piraq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piraq); err != nil {
				return err
			}
		}
	}
	for _, f := range piraq.ctx.Fields {
		if !platformidentityroleassignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if piraq.path != nil {
		prev, err := piraq.path(ctx)
		if err != nil {
			return err
		}
		piraq.sql = prev
	}
	return nil
}

func (piraq *PlatformIdentityRoleAssignmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PlatformIdentityRoleAssignment, error) {
	var (
		nodes       = []*PlatformIdentityRoleAssignment{}
		withFKs     = piraq.withFKs
		_spec       = piraq.querySpec()
		loadedTypes = [2]bool{
			piraq.withIdentity != nil,
			piraq.withRole != nil,
		}
	)
	if piraq.withIdentity != nil || piraq.withRole != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, platformidentityroleassignment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PlatformIdentityRoleAssignment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PlatformIdentityRoleAssignment{config: piraq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piraq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piraq.withIdentity; query != nil {
		if err := piraq.loadIdentity(ctx, query, nodes, nil,
			func(n *PlatformIdentityRoleAssignment, e *PlatformFederatedIdentity) { n.Edges.Identity = e }); err != nil {
			return nil, err
		}
	}
	if query := piraq.withRole; query != nil {
		if err := piraq.loadRole(ctx, query, nodes, nil,
			func(n *PlatformIdentityRoleAssignment, e *PlatformAppRole) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piraq *PlatformIdentityRoleAssignmentQuery) loadIdentity(ctx context.Context, query *PlatformFederatedIdentityQuery, nodes []*PlatformIdentityRoleAssignment, init func(*PlatformIdentityRoleAssignment), assign func(*PlatformIdentityRoleAssignment, *PlatformFederatedIdentity)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PlatformIdentityRoleAssignment)
	for i := range nodes {
		if nodes[i].platform_federated_identity_role_assignments == nil {
			continue
		}
		fk := *nodes[i].platform_federated_identity_role_assignments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(platformfederatedidentity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "platform_federated_identity_role_assignments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (piraq *PlatformIdentityRoleAssignmentQuery) loadRole(ctx context.Context, query *PlatformAppRoleQuery, nodes []*PlatformIdentityRoleAssignment, init func(*PlatformIdentityRoleAssignment), assign func(*PlatformIdentityRoleAssignment, *PlatformAppRole)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PlatformIdentityRoleAssignment)
	for i := range nodes {
		if nodes[i].platform_app_role_identity_assignments == nil {
			continue
		}
		fk := *nodes[i].platform_app_role_identity_assignments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(platformapprole.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "platform_app_role_identity_assignments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piraq *PlatformIdentityRoleAssignmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piraq.querySpec()
	_spec.Node.Columns = piraq.ctx.Fields
	if len(piraq.ctx.Fields) > 0 {
		_spec.Unique = piraq.ctx.Unique != nil && *piraq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piraq.driver, _spec)
}

func (piraq *PlatformIdentityRoleAssignmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(platformidentityroleassignment.Table, platformidentityroleassignment.Columns, sqlgraph.NewFieldSpec(platformidentityroleassignment.FieldID, field.TypeInt))
	_spec.From = piraq.sql
	if unique := piraq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piraq.path != nil {
		_spec.Unique = true
	}
	if fields := piraq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformidentityroleassignment.FieldID)
		for i := range fields {
			if fields[i] != platformidentityroleassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piraq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piraq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piraq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piraq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piraq *PlatformIdentityRoleAssignmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piraq.driver.Dialect())
	t1 := builder.Table(platformidentityroleassignment.Table)
	columns := piraq.ctx.Fields
	if len(columns) == 0 {
		columns = platformidentityroleassignment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piraq.sql != nil {
		selector = piraq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piraq.ctx.Unique != nil && *piraq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piraq.predicates {
		p(selector)
	}
	for _, p := range piraq.order {
		p(selector)
	}
	if offset := piraq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piraq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlatformIdentityRoleAssignmentGroupBy is the group-by builder for PlatformIdentityRoleAssignment entities.
type PlatformIdentityRoleAssignmentGroupBy struct {
	selector
	build *PlatformIdentityRoleAssignmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (piragb *PlatformIdentityRoleAssignmentGroupBy) Aggregate(fns ...AggregateFunc) *PlatformIdentityRoleAssignmentGroupBy {
	piragb.fns = append(piragb.fns, fns...)
	return piragb
}

// Scan applies the selector query and scans the result into the given value.
func (piragb *PlatformIdentityRoleAssignmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, piragb.build.ctx, ent.OpQueryGroupBy)
	if err := piragb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlatformIdentityRoleAssignmentQuery, *PlatformIdentityRoleAssignmentGroupBy](ctx, piragb.build, piragb, piragb.build.inters, v)
}

func (piragb *PlatformIdentityRoleAssignmentGroupBy) sqlScan(ctx context.Context, root *PlatformIdentityRoleAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(piragb.fns))
	for _, fn := range piragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*piragb.flds)+len(piragb.fns))
		for _, f := range *piragb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*piragb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := piragb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlatformIdentityRoleAssignmentSelect is the builder for selecting fields of PlatformIdentityRoleAssignment entities.
type PlatformIdentityRoleAssignmentSelect struct {
	*PlatformIdentityRoleAssignmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (piras *PlatformIdentityRoleAssignmentSelect) Aggregate(fns ...AggregateFunc) *PlatformIdentityRoleAssignmentSelect {
	piras.fns = append(piras.fns, fns...)
	return piras
}

// Scan applies the selector query and scans the result into the given value.
func (piras *PlatformIdentityRoleAssignmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, piras.ctx, ent.OpQuerySelect)
	if err := piras.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlatformIdentityRoleAssignmentQuery, *PlatformIdentityRoleAssignmentSelect](ctx, piras.PlatformIdentityRoleAssignmentQuery, piras, piras.inters, v)
}

func (piras *PlatformIdentityRoleAssignmentSelect) sqlScan(ctx context.Context, root *PlatformIdentityRoleAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(piras.fns))
	for _, fn := range piras.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*piras.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := piras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
