// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/platformuser"
	"github.com/dexidp/dex/storage/ent/db/predicate"
)

// PlatformUserDelete is the builder for deleting a PlatformUser entity.
type PlatformUserDelete struct {
	config
	hooks    []Hook
	mutation *PlatformUserMutation
}

// Where appends a list predicates to the PlatformUserDelete builder.
func (pud *PlatformUserDelete) Where(ps ...predicate.PlatformUser) *PlatformUserDelete {
	pud.mutation.Where(ps...)
	return pud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pud *PlatformUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pud.sqlExec, pud.mutation, pud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pud *PlatformUserDelete) ExecX(ctx context.Context) int {
	n, err := pud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pud *PlatformUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(platformuser.Table, sqlgraph.NewFieldSpec(platformuser.FieldID, field.TypeInt))
	if ps := pud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pud.mutation.done = true
	return affected, err
}

// PlatformUserDeleteOne is the builder for deleting a single PlatformUser entity.
type PlatformUserDeleteOne struct {
	pud *PlatformUserDelete
}

// Where appends a list predicates to the PlatformUserDelete builder.
func (pudo *PlatformUserDeleteOne) Where(ps ...predicate.PlatformUser) *PlatformUserDeleteOne {
	pudo.pud.mutation.Where(ps...)
	return pudo
}

// Exec executes the deletion query.
func (pudo *PlatformUserDeleteOne) Exec(ctx context.Context) error {
	n, err := pudo.pud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{platformuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pudo *PlatformUserDeleteOne) ExecX(ctx context.Context) {
	if err := pudo.Exec(ctx); err != nil {
		panic(err)
	}
}
