// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/predicate"
	"github.com/dexidp/dex/storage/ent/db/userapprole"
)

// UserAppRoleQuery is the builder for querying UserAppRole entities.
type UserAppRoleQuery struct {
	config
	ctx        *QueryContext
	order      []userapprole.OrderOption
	inters     []Interceptor
	predicates []predicate.UserAppRole
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserAppRoleQuery builder.
func (uarq *UserAppRoleQuery) Where(ps ...predicate.UserAppRole) *UserAppRoleQuery {
	uarq.predicates = append(uarq.predicates, ps...)
	return uarq
}

// Limit the number of records to be returned by this query.
func (uarq *UserAppRoleQuery) Limit(limit int) *UserAppRoleQuery {
	uarq.ctx.Limit = &limit
	return uarq
}

// Offset to start from.
func (uarq *UserAppRoleQuery) Offset(offset int) *UserAppRoleQuery {
	uarq.ctx.Offset = &offset
	return uarq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uarq *UserAppRoleQuery) Unique(unique bool) *UserAppRoleQuery {
	uarq.ctx.Unique = &unique
	return uarq
}

// Order specifies how the records should be ordered.
func (uarq *UserAppRoleQuery) Order(o ...userapprole.OrderOption) *UserAppRoleQuery {
	uarq.order = append(uarq.order, o...)
	return uarq
}

// First returns the first UserAppRole entity from the query.
// Returns a *NotFoundError when no UserAppRole was found.
func (uarq *UserAppRoleQuery) First(ctx context.Context) (*UserAppRole, error) {
	nodes, err := uarq.Limit(1).All(setContextOp(ctx, uarq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userapprole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uarq *UserAppRoleQuery) FirstX(ctx context.Context) *UserAppRole {
	node, err := uarq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserAppRole ID from the query.
// Returns a *NotFoundError when no UserAppRole ID was found.
func (uarq *UserAppRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uarq.Limit(1).IDs(setContextOp(ctx, uarq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userapprole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uarq *UserAppRoleQuery) FirstIDX(ctx context.Context) int {
	id, err := uarq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserAppRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserAppRole entity is found.
// Returns a *NotFoundError when no UserAppRole entities are found.
func (uarq *UserAppRoleQuery) Only(ctx context.Context) (*UserAppRole, error) {
	nodes, err := uarq.Limit(2).All(setContextOp(ctx, uarq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userapprole.Label}
	default:
		return nil, &NotSingularError{userapprole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uarq *UserAppRoleQuery) OnlyX(ctx context.Context) *UserAppRole {
	node, err := uarq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserAppRole ID in the query.
// Returns a *NotSingularError when more than one UserAppRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (uarq *UserAppRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uarq.Limit(2).IDs(setContextOp(ctx, uarq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userapprole.Label}
	default:
		err = &NotSingularError{userapprole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uarq *UserAppRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := uarq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserAppRoles.
func (uarq *UserAppRoleQuery) All(ctx context.Context) ([]*UserAppRole, error) {
	ctx = setContextOp(ctx, uarq.ctx, ent.OpQueryAll)
	if err := uarq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserAppRole, *UserAppRoleQuery]()
	return withInterceptors[[]*UserAppRole](ctx, uarq, qr, uarq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uarq *UserAppRoleQuery) AllX(ctx context.Context) []*UserAppRole {
	nodes, err := uarq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserAppRole IDs.
func (uarq *UserAppRoleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uarq.ctx.Unique == nil && uarq.path != nil {
		uarq.Unique(true)
	}
	ctx = setContextOp(ctx, uarq.ctx, ent.OpQueryIDs)
	if err = uarq.Select(userapprole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uarq *UserAppRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := uarq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uarq *UserAppRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uarq.ctx, ent.OpQueryCount)
	if err := uarq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uarq, querierCount[*UserAppRoleQuery](), uarq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uarq *UserAppRoleQuery) CountX(ctx context.Context) int {
	count, err := uarq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uarq *UserAppRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uarq.ctx, ent.OpQueryExist)
	switch _, err := uarq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uarq *UserAppRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := uarq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserAppRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uarq *UserAppRoleQuery) Clone() *UserAppRoleQuery {
	if uarq == nil {
		return nil
	}
	return &UserAppRoleQuery{
		config:     uarq.config,
		ctx:        uarq.ctx.Clone(),
		order:      append([]userapprole.OrderOption{}, uarq.order...),
		inters:     append([]Interceptor{}, uarq.inters...),
		predicates: append([]predicate.UserAppRole{}, uarq.predicates...),
		// clone intermediate query.
		sql:  uarq.sql.Clone(),
		path: uarq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (uarq *UserAppRoleQuery) GroupBy(field string, fields ...string) *UserAppRoleGroupBy {
	uarq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserAppRoleGroupBy{build: uarq}
	grbuild.flds = &uarq.ctx.Fields
	grbuild.label = userapprole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (uarq *UserAppRoleQuery) Select(fields ...string) *UserAppRoleSelect {
	uarq.ctx.Fields = append(uarq.ctx.Fields, fields...)
	sbuild := &UserAppRoleSelect{UserAppRoleQuery: uarq}
	sbuild.label = userapprole.Label
	sbuild.flds, sbuild.scan = &uarq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserAppRoleSelect configured with the given aggregations.
func (uarq *UserAppRoleQuery) Aggregate(fns ...AggregateFunc) *UserAppRoleSelect {
	return uarq.Select().Aggregate(fns...)
}

func (uarq *UserAppRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uarq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uarq); err != nil {
				return err
			}
		}
	}
	for _, f := range uarq.ctx.Fields {
		if !userapprole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if uarq.path != nil {
		prev, err := uarq.path(ctx)
		if err != nil {
			return err
		}
		uarq.sql = prev
	}
	return nil
}

func (uarq *UserAppRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserAppRole, error) {
	var (
		nodes   = []*UserAppRole{}
		withFKs = uarq.withFKs
		_spec   = uarq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userapprole.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserAppRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserAppRole{config: uarq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uarq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uarq *UserAppRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uarq.querySpec()
	_spec.Node.Columns = uarq.ctx.Fields
	if len(uarq.ctx.Fields) > 0 {
		_spec.Unique = uarq.ctx.Unique != nil && *uarq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uarq.driver, _spec)
}

func (uarq *UserAppRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userapprole.Table, userapprole.Columns, sqlgraph.NewFieldSpec(userapprole.FieldID, field.TypeInt))
	_spec.From = uarq.sql
	if unique := uarq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uarq.path != nil {
		_spec.Unique = true
	}
	if fields := uarq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userapprole.FieldID)
		for i := range fields {
			if fields[i] != userapprole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uarq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uarq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uarq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uarq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uarq *UserAppRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uarq.driver.Dialect())
	t1 := builder.Table(userapprole.Table)
	columns := uarq.ctx.Fields
	if len(columns) == 0 {
		columns = userapprole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uarq.sql != nil {
		selector = uarq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uarq.ctx.Unique != nil && *uarq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uarq.predicates {
		p(selector)
	}
	for _, p := range uarq.order {
		p(selector)
	}
	if offset := uarq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uarq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserAppRoleGroupBy is the group-by builder for UserAppRole entities.
type UserAppRoleGroupBy struct {
	selector
	build *UserAppRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uargb *UserAppRoleGroupBy) Aggregate(fns ...AggregateFunc) *UserAppRoleGroupBy {
	uargb.fns = append(uargb.fns, fns...)
	return uargb
}

// Scan applies the selector query and scans the result into the given value.
func (uargb *UserAppRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uargb.build.ctx, ent.OpQueryGroupBy)
	if err := uargb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAppRoleQuery, *UserAppRoleGroupBy](ctx, uargb.build, uargb, uargb.build.inters, v)
}

func (uargb *UserAppRoleGroupBy) sqlScan(ctx context.Context, root *UserAppRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uargb.fns))
	for _, fn := range uargb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uargb.flds)+len(uargb.fns))
		for _, f := range *uargb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uargb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uargb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserAppRoleSelect is the builder for selecting fields of UserAppRole entities.
type UserAppRoleSelect struct {
	*UserAppRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uars *UserAppRoleSelect) Aggregate(fns ...AggregateFunc) *UserAppRoleSelect {
	uars.fns = append(uars.fns, fns...)
	return uars
}

// Scan applies the selector query and scans the result into the given value.
func (uars *UserAppRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uars.ctx, ent.OpQuerySelect)
	if err := uars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAppRoleQuery, *UserAppRoleSelect](ctx, uars.UserAppRoleQuery, uars, uars.inters, v)
}

func (uars *UserAppRoleSelect) sqlScan(ctx context.Context, root *UserAppRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uars.fns))
	for _, fn := range uars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
