// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/userapprole"
)

// UserAppRoleCreate is the builder for creating a UserAppRole entity.
type UserAppRoleCreate struct {
	config
	mutation *UserAppRoleMutation
	hooks    []Hook
}

// Mutation returns the UserAppRoleMutation object of the builder.
func (uarc *UserAppRoleCreate) Mutation() *UserAppRoleMutation {
	return uarc.mutation
}

// Save creates the UserAppRole in the database.
func (uarc *UserAppRoleCreate) Save(ctx context.Context) (*UserAppRole, error) {
	return withHooks(ctx, uarc.sqlSave, uarc.mutation, uarc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uarc *UserAppRoleCreate) SaveX(ctx context.Context) *UserAppRole {
	v, err := uarc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uarc *UserAppRoleCreate) Exec(ctx context.Context) error {
	_, err := uarc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uarc *UserAppRoleCreate) ExecX(ctx context.Context) {
	if err := uarc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uarc *UserAppRoleCreate) check() error {
	return nil
}

func (uarc *UserAppRoleCreate) sqlSave(ctx context.Context) (*UserAppRole, error) {
	if err := uarc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uarc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uarc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uarc.mutation.id = &_node.ID
	uarc.mutation.done = true
	return _node, nil
}

func (uarc *UserAppRoleCreate) createSpec() (*UserAppRole, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAppRole{config: uarc.config}
		_spec = sqlgraph.NewCreateSpec(userapprole.Table, sqlgraph.NewFieldSpec(userapprole.FieldID, field.TypeInt))
	)
	return _node, _spec
}

// UserAppRoleCreateBulk is the builder for creating many UserAppRole entities in bulk.
type UserAppRoleCreateBulk struct {
	config
	err      error
	builders []*UserAppRoleCreate
}

// Save creates the UserAppRole entities in the database.
func (uarcb *UserAppRoleCreateBulk) Save(ctx context.Context) ([]*UserAppRole, error) {
	if uarcb.err != nil {
		return nil, uarcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uarcb.builders))
	nodes := make([]*UserAppRole, len(uarcb.builders))
	mutators := make([]Mutator, len(uarcb.builders))
	for i := range uarcb.builders {
		func(i int, root context.Context) {
			builder := uarcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAppRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uarcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uarcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uarcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uarcb *UserAppRoleCreateBulk) SaveX(ctx context.Context) []*UserAppRole {
	v, err := uarcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uarcb *UserAppRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := uarcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uarcb *UserAppRoleCreateBulk) ExecX(ctx context.Context) {
	if err := uarcb.Exec(ctx); err != nil {
		panic(err)
	}
}
