// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dexidp/dex/storage/ent/db/userapprole"
)

// UserAppRole is the model entity for the UserAppRole schema.
type UserAppRole struct {
	config
	// ID of the ent.
	ID                        int `json:"id,omitempty"`
	platform_user_assignments *int
	selectValues              sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAppRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userapprole.FieldID:
			values[i] = new(sql.NullInt64)
		case userapprole.ForeignKeys[0]: // platform_user_assignments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAppRole fields.
func (uar *UserAppRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userapprole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uar.ID = int(value.Int64)
		case userapprole.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field platform_user_assignments", value)
			} else if value.Valid {
				uar.platform_user_assignments = new(int)
				*uar.platform_user_assignments = int(value.Int64)
			}
		default:
			uar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAppRole.
// This includes values selected through modifiers, order, etc.
func (uar *UserAppRole) Value(name string) (ent.Value, error) {
	return uar.selectValues.Get(name)
}

// Update returns a builder for updating this UserAppRole.
// Note that you need to call UserAppRole.Unwrap() before calling this method if this UserAppRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (uar *UserAppRole) Update() *UserAppRoleUpdateOne {
	return NewUserAppRoleClient(uar.config).UpdateOne(uar)
}

// Unwrap unwraps the UserAppRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uar *UserAppRole) Unwrap() *UserAppRole {
	_tx, ok := uar.config.driver.(*txDriver)
	if !ok {
		panic("db: UserAppRole is not a transactional entity")
	}
	uar.config.driver = _tx.drv
	return uar
}

// String implements the fmt.Stringer.
func (uar *UserAppRole) String() string {
	var builder strings.Builder
	builder.WriteString("UserAppRole(")
	builder.WriteString(fmt.Sprintf("id=%v", uar.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserAppRoles is a parsable slice of UserAppRole.
type UserAppRoles []*UserAppRole
